import '../styles/globals.css';

import AuthProvider from '@/contexts/AuthProvider';
import GameProvider from '@/contexts/GameProvider';
import Navbar from '@/components/navbar/Navbar';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
	subsets: ['latin'],
	display: 'swap',
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
	title: 'CATching Game App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<head>
				<link rel='icon' href='/icon.ico' sizes='any' />
			</head>
			<body
				className={`${poppins.className} uppercase font-semibold text-base text-white bg-green-500 flex flex-col`}
			>
				<AuthProvider>
					<GameProvider>
						<Navbar />
						{children}
					</GameProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
